package com.project.code.Model;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

/**
 * Entity representing the stock of a specific product within a specific
 * store.
 *
 * <p>The {@code Inventory} entity acts as a junction between the
 * {@link Product} and {@link Store} entities, modelling the fact that a
 * given product may be held in the inventory of several stores and that
 * a given store may hold several products. Each inventory entry records
 * the current stock level of a product at a particular location.</p>
 */
@Entity
public class Inventory {

    /**
     * Unique identifier of the inventory entry. It is automatically
     * generated by the database using an identity-based strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * Product that this inventory entry refers to.
     *
     * <p>This field represents the owning side of the relationship with
     * {@link Product}. The {@code @JsonBackReference} annotation, using
     * the same identifier as the corresponding {@code @JsonManagedReference}
     * on {@code Product}, ensures that the product is not serialised
     * again from this side, preventing infinite recursion.</p>
     */
    @ManyToOne
    @JoinColumn(name = "product_id")
    @JsonBackReference("inventory-product")
    private Product product;

    /**
     * Store where the inventory entry is held.
     *
     * <p>This field represents the owning side of the relationship with
     * {@link Store}. The {@code @JsonBackReference} annotation, using
     * the same identifier as the corresponding {@code @JsonManagedReference}
     * on {@code Store}, ensures that the store is not serialised again
     * from this side, preventing infinite recursion.</p>
     */
    @ManyToOne
    @JoinColumn(name = "store_id")
    @JsonBackReference("inventory-store")
    private Store store;

    /**
     * Current stock level of the product at the associated store.
     * This value reflects the number of units available at the moment
     * the record is read.
     */
    private Integer stockLevel;

    /**
     * Default no-argument constructor required by JPA.
     */
    public Inventory() {
    }

    /**
     * Constructs an inventory entry with the given product, store and
     * stock level.
     *
     * @param product    the product held in inventory
     * @param store      the store where the product is held
     * @param stockLevel the current stock level of the product
     */
    public Inventory(Product product, Store store, Integer stockLevel) {
        this.product = product;
        this.store = store;
        this.stockLevel = stockLevel;
    }

    /**
     * Retrieves the inventory entry identifier.
     *
     * @return the unique identifier of the inventory entry
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the inventory entry identifier.
     *
     * @param id the unique identifier to assign
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Retrieves the product associated with this inventory entry.
     *
     * @return the product held in inventory
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Sets the product associated with this inventory entry.
     *
     * @param product the product to assign
     */
    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * Retrieves the store associated with this inventory entry.
     *
     * @return the store where the inventory is held
     */
    public Store getStore() {
        return store;
    }

    /**
     * Sets the store associated with this inventory entry.
     *
     * @param store the store to assign
     */
    public void setStore(Store store) {
        this.store = store;
    }

    /**
     * Retrieves the current stock level of the product.
     *
     * @return the current stock level
     */
    public Integer getStockLevel() {
        return stockLevel;
    }

    /**
     * Sets the current stock level of the product.
     *
     * @param stockLevel the stock level to assign
     */
    public void setStockLevel(Integer stockLevel) {
        this.stockLevel = stockLevel;
    }
}
