package com.project.code.Model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;

/**
 * Entity representing an order placed by a customer at a given store.
 *
 * <p>An order captures the commercial transaction performed by a customer:
 * it identifies the customer who placed it, the store that fulfilled it,
 * the total monetary amount and the timestamp of creation. Additionally,
 * it aggregates one or more {@link OrderItem} instances that describe the
 * individual products included in the transaction.</p>
 */
@Entity
public class OrderDetails {

    /**
     * Unique identifier of the order. It is automatically generated by
     * the database using an identity-based strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Customer who placed the order.
     *
     * <p>This field represents the owning side of the relationship with
     * {@link Customer}. The {@code @JsonBackReference} annotation uses the
     * same identifier declared on the {@code Customer} side
     * ({@code "customer-orders"}) so that Jackson can correctly pair both
     * annotations and prevent infinite recursion during serialisation.</p>
     */
    @ManyToOne
    @JoinColumn(name = "customer_id")
    @JsonBackReference("customer-orders")
    private Customer customer;

    /**
     * Store from which the order was placed.
     *
     * <p>This field identifies the physical or virtual location responsible
     * for fulfilling the order. The relationship is unidirectional: the
     * {@link Store} entity does not maintain a collection of orders, so no
     * matching {@code @JsonBackReference} exists on the other side.</p>
     */
    @ManyToOne
    @JoinColumn(name = "store_id")
    @JsonManagedReference
    private Store store;

    /**
     * Total monetary value of the order, computed as the sum of the prices
     * of all its line items.
     */
    private Double totalPrice;

    /**
     * Date and time at which the order was placed.
     */
    private LocalDateTime date;

    /**
     * Collection of line items that compose this order.
     *
     * <p>The relationship is bidirectional: the {@code mappedBy} attribute
     * indicates that the {@code order} field in {@link OrderItem} owns the
     * foreign key. The {@code @JsonManagedReference} annotation ensures
     * that this side of the relationship is serialised, while the matching
     * {@code @JsonBackReference} on the {@link OrderItem} side prevents
     * infinite recursion during JSON serialisation.</p>
     */
    @OneToMany(mappedBy = "order", fetch = FetchType.EAGER)
    @JsonManagedReference("order-items")
    private List<OrderItem> orderItems = new ArrayList<>();

    /**
     * Default no-argument constructor required by JPA.
     */
    public OrderDetails() {
    }

    /**
     * Constructs an order with the given customer, store, total price and
     * timestamp.
     *
     * @param customer   the customer who placed the order
     * @param store      the store that fulfils the order
     * @param totalPrice the total monetary value of the order
     * @param date       the date and time at which the order was placed
     */
    public OrderDetails(Customer customer, Store store, Double totalPrice, LocalDateTime date) {
        this.customer = customer;
        this.store = store;
        this.totalPrice = totalPrice;
        this.date = date;
    }

    /**
     * Retrieves the order identifier.
     *
     * @return the unique identifier of the order
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the order identifier.
     *
     * @param id the unique identifier to assign
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Retrieves the customer who placed the order.
     *
     * @return the customer associated with the order
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the customer who placed the order.
     *
     * @param customer the customer to assign
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * Retrieves the store that fulfils the order.
     *
     * @return the store associated with the order
     */
    public Store getStore() {
        return store;
    }

    /**
     * Sets the store that fulfils the order.
     *
     * @param store the store to assign
     */
    public void setStore(Store store) {
        this.store = store;
    }

    /**
     * Retrieves the total monetary value of the order.
     *
     * @return the total price of the order
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the total monetary value of the order.
     *
     * @param totalPrice the total price to assign
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * Retrieves the timestamp at which the order was placed.
     *
     * @return the date and time of the order
     */
    public LocalDateTime getDate() {
        return date;
    }

    /**
     * Sets the timestamp at which the order was placed.
     *
     * @param date the date and time to assign
     */
    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    /**
     * Retrieves the list of line items that compose the order.
     *
     * @return the list of order items
     */
    public List<OrderItem> getOrderItems() {
        return orderItems;
    }

    /**
     * Sets the list of line items that compose the order.
     *
     * @param orderItems the list of order items to assign
     */
    public void setOrderItems(List<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }
}
