package com.project.code.Model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import jakarta.validation.constraints.NotNull;

/**
 * Document representing a customer review of a product.
 *
 * <p>Unlike the other entities in this project, {@code Review} is stored
 * in MongoDB rather than in the relational MySQL database. The choice of
 * a document-oriented store is motivated by the flexible and schema-less
 * nature of user-generated content: reviews may evolve over time to
 * include new fields (e.g. images, reactions, replies) without requiring
 * migrations of the underlying schema.</p>
 *
 * <p>Each review identifies the customer who wrote it, the product being
 * reviewed and the store through which the product was acquired. It also
 * records a numeric rating (from 1 to 5) and an optional free-text
 * comment.</p>
 */
@Document(collection = "reviews")
public class Review {

    /**
     * Unique identifier of the review. The value is automatically
     * generated by MongoDB when the document is inserted and is
     * represented as a hexadecimal string.
     */
    @Id
    private String id;

    /**
     * Identifier of the customer who created the review. This field is
     * mandatory and must reference an existing customer.
     */
    @NotNull(message = "Customer cannot be null")
    private Long customerId;

    /**
     * Identifier of the product being reviewed. This field is mandatory
     * and must reference an existing product.
     */
    @NotNull(message = "Product cannot be null")
    private Long productId;

    /**
     * Identifier of the store associated with the product reviewed.
     * This field is mandatory.
     */
    @NotNull(message = "Store cannot be null")
    private Long storeId;

    /**
     * Rating assigned to the product, typically expressed on a scale
     * from 1 to 5. This field is mandatory.
     */
    @NotNull(message = "Rating cannot be null")
    private Integer rating;

    /**
     * Optional free-text comment provided by the customer. This field
     * may be {@code null} if the customer did not include a comment
     * with the rating.
     */
    private String comment;

    /**
     * Default no-argument constructor required by Spring Data MongoDB.
     */
    public Review() {
    }

    /**
     * Constructs a review with the given identifiers, rating and an
     * optional comment.
     *
     * @param customerId identifier of the customer who wrote the review
     * @param productId  identifier of the product being reviewed
     * @param storeId    identifier of the store associated with the product
     * @param rating     rating assigned to the product (typically 1-5)
     * @param comment    optional free-text comment
     */
    public Review(Long customerId, Long productId, Long storeId, Integer rating, String comment) {
        this.customerId = customerId;
        this.productId = productId;
        this.storeId = storeId;
        this.rating = rating;
        this.comment = comment;
    }

    /**
     * Retrieves the review identifier.
     *
     * @return the MongoDB-generated identifier of the review
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the review identifier.
     *
     * @param id the identifier to assign
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Retrieves the identifier of the customer who wrote the review.
     *
     * @return the customer identifier
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * Sets the identifier of the customer who wrote the review.
     *
     * @param customerId the customer identifier to assign
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * Retrieves the identifier of the product being reviewed.
     *
     * @return the product identifier
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * Sets the identifier of the product being reviewed.
     *
     * @param productId the product identifier to assign
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Retrieves the identifier of the store associated with the product.
     *
     * @return the store identifier
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * Sets the identifier of the store associated with the product.
     *
     * @param storeId the store identifier to assign
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * Retrieves the rating assigned to the product.
     *
     * @return the rating value
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * Sets the rating assigned to the product.
     *
     * @param rating the rating value to assign
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * Retrieves the optional free-text comment of the review.
     *
     * @return the comment, or {@code null} if none was provided
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the optional free-text comment of the review.
     *
     * @param comment the comment to assign
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}