package com.project.code.Model;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * Entity representing a physical or virtual store within the system.
 *
 * <p>A store is a location where products are held in inventory and from
 * which customer orders may be fulfilled. Each store maintains its own
 * stock levels through the {@link Inventory} entity, establishing a
 * one-to-many relationship between the store and its inventory entries.</p>
 */
@Entity
public class Store {

    /**
     * Unique identifier of the store. It is automatically generated by
     * the database using an identity-based strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * Commercial name of the store. This field is mandatory and must
     * contain at least one non-whitespace character.
     */
    @NotNull(message = "Name cannot be null")
    @NotBlank(message = "Name cannot be blank")
    private String name;

    /**
     * Physical address of the store. This field is mandatory and must
     * contain at least one non-whitespace character.
     */
    @NotNull(message = "Address cannot be null")
    @NotBlank(message = "Address cannot be blank")
    private String address;

    /**
     * Collection of inventory entries associated with this store.
     *
     * <p>The relationship is bidirectional: the {@code mappedBy} attribute
     * indicates that the {@code store} field in {@link Inventory} owns
     * the foreign key. The {@code @JsonManagedReference} annotation ensures
     * that this side of the relationship is serialised, while the matching
     * {@code @JsonBackReference} in {@link Inventory} prevents infinite
     * recursion during JSON serialisation.</p>
     */
    @OneToMany(mappedBy = "store", fetch = FetchType.EAGER)
    @JsonManagedReference("inventory-store")
    private List<Inventory> inventory = new ArrayList<>();

    /**
     * Default no-argument constructor required by JPA.
     */
    public Store() {
    }

    /**
     * Constructs a store with the given name and address.
     *
     * @param name    the commercial name of the store
     * @param address the physical address of the store
     */
    public Store(String name, String address) {
        this.name = name;
        this.address = address;
    }

    /**
     * Retrieves the store identifier.
     *
     * @return the unique identifier of the store
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the store identifier.
     *
     * @param id the unique identifier to assign
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Retrieves the store's commercial name.
     *
     * @return the name of the store
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the store's commercial name.
     *
     * @param name the name to assign
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Retrieves the store's physical address.
     *
     * @return the address of the store
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the store's physical address.
     *
     * @param address the address to assign
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Retrieves the list of inventory entries associated with this store.
     *
     * @return the list of inventory entries held by the store
     */
    public List<Inventory> getInventory() {
        return inventory;
    }

    /**
     * Sets the list of inventory entries associated with this store.
     *
     * @param inventory the list of inventory entries to assign
     */
    public void setInventory(List<Inventory> inventory) {
        this.inventory = inventory;
    }
}
